### ISSUE TITLE
Object Placement string writing

### ISSUE THREAD

**Issue by Knuxfan24** [Big-Endian-32/Marathon#17]
When reading, the reader is successfully able to read Japanese characters, but is unable to properly write them, instead writing a question mark in its place.

When reading:
![image](https://user-images.githubusercontent.com/10520977/142149133-2646903d-a7f9-49ee-8413-cfb02df301b5.png)

After saving and reading the saved file:
![image](https://user-images.githubusercontent.com/10520977/142149082-a44d8685-4898-4ca0-a7e9-873d0642c6df.png)

**Comment by Knuxfan24** [comment]
Issue seems to lie in the BINAWriter's string writer, as it is added to the list of strings to write correctly.

**Comment by HyperBE32** [comment]
This should now be fixed as of commit https://github.com/Big-Endian-32/Marathon/commit/f3d8c06617b6c3e0f4ceb72b63362d943e6a451d.

**Comment by Knuxfan24** [comment]
Confirmed to be fixed by the above commit through usage in the Randomiser now demonstrating expected behaviour.
